FROM python:3.8.16-slim-bullseye
LABEL maintainer="zeenfts"

ENV KAFKA_HOME=/usr/consumer

RUN apt-get -yqq update && apt-get -yqq install git
RUN python -m pip install --upgrade pip setuptools wheel --no-cache-dir

WORKDIR $KAFKA_HOME
# VOLUME /usr

VOLUME ../app/consumer.py :/usr/consumer/consumer.py

RUN pip install confluent_kafka
RUN pip install --upgrade git+https://github.com/twintproject/twint.git@origin/master#egg=twint

ENTRYPOINT ["python", "./consumer.py"]